import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  inputs: {
    height: 40,
    paddingLeft: 10,
    marginTop: 5,
    marginBottom: 5,
    fontSize: 14,
    marginLeft: "auto",
    marginRight: "auto",
    width: "95%",
  },
  inputsLogin: {
    height: 40,
    paddingLeft: 10,
    borderWidth: 1,
    borderRadius: 5,
    fontFamily: "OpenSans-Regular",
    placeholderTextColor: "#cb3065",
    borderColor: "#b58de8",
    width: "85%",
  },
  error: {
    color: "#cB3065",
    fontSize: 13,
    fontFamily: "OpenSans-Regular",
    marginLeft: "15%",
    marginBottom: 5,
  },
  inputsText: {
    fontSize: 16,
    color: "#F23B6C",
    marginLeft: "5%",
    fontFamily: "Bree-Serif",
    paddingLeft: 15,
    marginTop: 10,
  },
  dialogText: {
    color: "#F23B6C",
    fontFamily: "Bree-Serif",
    marginTop: 10,
  },
  containerInput: {
    flexDirection: "row",
    alignItems: "center",
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
    fontFamily: "Bree-Serif",
    marginTop: 5,
  },
  containerInputSolo: {
    alignItems: "center",
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
    fontFamily: "Bree-Serif",
    marginTop: 5,
    marginBottom: 10,
  },
  containerButton: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 10,
    flexDirection: "row",
  },
  button: {
    alignItems: "center",
    backgroundColor: "#f23b6c",
    borderColor: "#f23b6c",
    width: "50%",
    height: "2.5rem",
    borderWidth: 2,
    borderRadius: 10,
    padding: 5,
    margin: 10,
  },
  textButton: {
    color: "#ffffff",
    fontSize: "1rem",
    fontFamily: "Bree-Serif",
    textAlign: "center",
  },
  buttonSecondary: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#f23b6c",
    width: "50%",
    height: "2.5rem",
    borderWidth: 2,
    borderRadius: 10,
    padding: 5,
    margin: 5,
  },
  textButtonSecondary: {
    color: "#f23b6c",
    fontSize: "1rem",
    fontFamily: "Bree-Serif",
    justifyContent: "center",
  },
  fixToText: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  forgottenPassword: {
    textAlign: "center",
    padding: 5,
    fontFamily: "OpenSans-Regular",
    color: "#cb3065",
  },
  help: {
    textAlign: "center",
    marginBottom: 15,
    padding: 5,
    fontFamily: "OpenSans-Regular",
    color: "#cb3065",
  },
});
